### ISSUE TITLE
Make the tab's shell configurable

### ISSUE THREAD

**Issue by TheTeXnician** [austinjones/tab-rs#177]
After playing with tab for some time, I'm very happy with the tool and its capabilities. One option I am missing though: specifying the shell to run when the tab is started. Something like the following configuration (based on your example) would be great:

```
repo: proj
doc: "my project"

tabs:
  - tab: run
    dir: src/
    shell: /usr/bin/fish
    doc: "runs the project server"
```

As an explanation: I'm using `fish` shell regularly but due to some compatibility issues of that shell my login shell is `zsh`. So `tab proj/run/` will start a shell with `zsh`. Some other use cases include me wanting to use `bash` in certain projects because I want to restrict myself to features of `bash` when working e.g. on trying commands to include in containers whereas my development environment shall stay comfortable.
