### ISSUE TITLE
Add empty/no-tab option to new fuzzy finder

### ISSUE THREAD

**Issue by jcvar** [austinjones/tab-rs#224]
I'd like to propose that the fuzzy finder's default selection be: disconnect from the current session. That way, `ctrl-t <enter>` matches the behavior of `ctrl-w` prior to 0.5.

Thank you for the work in this project.

**Comment by austinjones** [comment]
Hi @jcvar,
`ctrl-T ESC` should do what you need.  That's how I get back to my root shell now.  I'm being quite cautious with keybindings because there are so many conflicts with other CLI tools.

Also, if you want ctrl-W back, you can bind it in `~/.config/tab.yml`:
```
key_bindings:
  - action: Disconnect
    keys: ctrl-W
  - action: SelectInteractive
    keys: ctrl-T

workspace: []
```

I have been thinking about the behavior when you enter input that doesn't match any tabs.  Right now the finder exits to the tab you launched it from, but I'm considering changing the behavior to 'create a tab with this name'.
