### ISSUE TITLE
can tab-rs run commands automatically

### ISSUE THREAD

**Issue by FuGangqiang** [austinjones/tab-rs#247]
tab.yml config is awesome，but can tab.yml config the init commands of each tab:

```
repo: proj
doc: "my project"

tabs:
  - tab: run
    dir: src/
    doc: "runs the project server"
    commands:
      - echo "start server"
      - python -m http.server
```
