### ISSUE TITLE
In the fuzzy finder, make 'new tab' optional

### ISSUE THREAD

**Issue by austinjones** [austinjones/tab-rs#324]
Allow user configuration of whether the `(new tab)` option in the fuzzy finder is visible.  Config example:
```
fuzzy:
  create_tab: true

workspace:
  - workspace: ~/my_workspace
```
