### ISSUE TITLE
Option to change Tab Color of Fuzzy Finder

### ISSUE THREAD

**Issue by guy-who-googles** [austinjones/tab-rs#353]
Similar to #45, but to change the base color of tabs in fuzzy finder.

Maybe it's just me, but blue is difficult to see in my terminal (Alacritty). While a color configuration option would help my specific use case, pairing it to a grouping of tabs (seems like workspace/repo abstraction may change depending on #315 - specifically [this](https://github.com/austinjones/tab-rs/issues/315#issuecomment-761537905)) would be useful when you start using a lot more tabs and variants. I'm still working towards building my configuration towards the advanced use case below, so sorry if the syntax isn't 100%, but hopefully it gets the idea across.

~/.config/tab.yml
```
workspace:
    - workspace: proj1
      color: green
    - workspace: proj2
      color: orange
```
~/proj1/tab.yml
```
workspace:
    - repo:  mobile
      color: light_green
    - repo: website
      color: dark_green
```
~/proj2/tab.yml
```
workspace:
    - tab: main_branch
    #color inherited from top level
    - tab:   branch_with_changes_that_make_all_the_things_better
      color: light_orange
    - tab:   branch_that_probably_wont
      color: dark_orange
```
